## Практическое задание 2.1

In [1]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;  
    
Вспомним, что что матрицу $A$ можно умножить не на всякую матрицу $B$: __необходимо, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.__   
По этому правилу видим, что произведение $AB$ не определено и произведение $BA$ также не определено 

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$   
По этому правилу видим, что  произведение $AB$ определено (размер новой матрицы 2x3), а произведение $BA$ не определено

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$  
По этому правилу видим, что  произведение $AB$ определено (размер новой матрицы 8x8) и произведение $BA$ также определено (размер новой матрицы 3x3)    

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$  
По этому правилу видим, что  произведение $AB$ определено и произведение $BA$ также определено (размер обоих новых матриц 4x4)      

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$  
Сумма данных матриц равна:
$С=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$  
Проврим

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

A + B

array([[ 5, -3],
       [ 3,  5]])

Видим, что мои расчеты оказались верными

Призведение я посчитаю с помощью моей функции из 4 задания. Данная функция работает без numpy, а следовательно я разобрался в том, как перемножаются матрицы и здесь нет смысла переписывать это.

In [3]:
def product_matrices(A, B):
    if A.shape[1] != B.shape[0]:
        print(f'Матрицу c размером {A.shape} нельзя перемножить на матрицу с размером {B.shape}')
    else:
        С = [[0 for i in range(A.shape[0])] for i in range(B.T.shape[0])]

        for i in range(A.shape[0]):
            for j in range(B.T.shape[0]):
                for k in range(B.shape[0]):
                    С[i][j] = С[i][j] +  (A[i, k] * B.T[j, k])
    return С 

In [4]:
np.array(product_matrices(A, B))

array([[  4, -11],
       [ 12,  -3]])

Проверим

In [5]:
A @ B

array([[  4, -11],
       [ 12,  -3]])

Видим, что произведение посчитано правильно

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

Зададим матрицы

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

Воспользуемся для рассчетов функцией произведения матрифы на число без использования numpy.

In [7]:
def product_matric_num(A, B):
    for i in range(B.shape[0]):
        for j in range(B.shape[1]):
            B[i][j] = A * B[i][j]
            
    return B      

In [8]:
product_matric_num(3, A) - product_matric_num(2, B) + product_matric_num(4, C)

array([[ 11,  -5],
       [  9, -12]])

Проверим расчеты

In [9]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3 * A - 2 * B  + 4 * C 

array([[ 11,  -5],
       [  9, -12]])

Видим, что расчеты прведены верно

__4*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [10]:
A = np.array([[1, 0], [2, 1], [10, 5]])
B = np.array([[2, 0, 0], [0, 0, 1]])

In [11]:
def product_matrices(A, B):
    if A.shape[1] != B.shape[0]:
        print(f'Матрицу c размером {A.shape} нельзя перемножить на матрицу с размером {B.shape}')
    else:
        С = [[0 for i in range(A.shape[0])] for i in range(B.T.shape[0])]

        for i in range(A.shape[0]):
            for j in range(B.T.shape[0]):
                for k in range(B.shape[0]):
                    С[i][j] = С[i][j] +  (A[i, k] * B.T[j, k])
    return С      

In [12]:
product_matrices(A, B)

[[2, 0, 0], [4, 0, 1], [20, 0, 5]]

В более привычном виде:

In [13]:
np.array(product_matrices(A, B))

array([[ 2,  0,  0],
       [ 4,  0,  1],
       [20,  0,  5]])

Проверим правильность перемножения с помощью средств numpy

In [14]:
A @ B

array([[ 2,  0,  0],
       [ 4,  0,  1],
       [20,  0,  5]])

Видим, что все считается правильно