## Практическое задание 4.1

In [1]:
import sympy as sym
import numpy as np
np.set_printoptions(precision=2, suppress=True)
import warnings
warnings.filterwarnings("ignore")

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Преобразуем расширенную матрицу системы путем элементарных преобразований:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Вычтем из 3 строки 1

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Вычтим из 2 строки 1, умноженную на 2

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Мы видим, что система имеет _бесконечное количество решений._ Запишем его в виде _общего решения_.

Оставшаяся матрица соответствует системе

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$$

В данном случае можно рассматривать в качестве _свободного_ параметра $x_{4}=c$. Тогда, выражая остальные переменные через $c$, получим:

$$x_{4}=c,$$
$$x_{3} = -2+3/2\cdot с,$$
$$x_{2}  = 13/2\cdot c,$$
$$x_{1}  = -2-3\cdot c.$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$  

Поскольку я самостоятельно написал функцию для решения уравнений методом Гауса, то я достаточно хорошо с ним разобрался и здесь для экономии времени предлагаю использовать данную функцию.  
Запишем уравнение в матричном виде и воспользуемся функцией.

In [2]:
A = np.array([[3., -1., 1., 4.], [2., -5., -3., -17.], [1., 1., -1., 0.]])
A

array([[  3.,  -1.,   1.,   4.],
       [  2.,  -5.,  -3., -17.],
       [  1.,   1.,  -1.,   0.]])

In [3]:
def solv_equations(A):
    for nrow in range(len(A)):
        for i in range(nrow + 1):
            if nrow != len(A) - 1:
                A[nrow + 1] = A[nrow + 1] - A[i] * (A[nrow + 1][i] / A[i][i])
            else:
                break
    print("Диагональная матрица:")
    print(A)
    roots = []
    if np.count_nonzero(A[len(A)-1])==2:
        for i in reversed(range(1, len(A) + 1)):
            x = (A[i - 1][len(A)] / A[i - 1][i - 1])
            roots.append(x)
            A[:, i - 1] = A[:, i - 1] * x
            A[:, len(A)] = A[:, len(A)] - A[:, i - 1]
        print("Данная СЛАУ является совместной со следующими корнями: ", roots[::-1])
        
    elif np.count_nonzero(A[len(A)-1]) < 2 or np.count_nonzero(A[len(A)-2]) < 2:
        print("Диагональная матрица:")
        print(A)
        print("Данная СЛАУ является несовместной и решений не имеет")
    
    elif np.count_nonzero(A[len(A)-1]) > 2:
        print("Диагональная матрица:")
        print(A)
        print("Данная СЛАУ является совместной и имеет бесконечное множество решений")  

In [4]:
solv_equations(A)

Диагональная матрица:
[[  3.    -1.     1.     4.  ]
 [  0.    -4.33  -3.67 -19.67]
 [  0.     0.    -2.46  -7.38]]
Данная СЛАУ является совместной со следующими корнями:  [1.0000000000000002, 2.0000000000000004, 3.0]


Проверим

In [5]:
M1 = np.array([[3., -1., 1.], [2, -5, -3], [1, 1, -1]])
v1 = np.array([4., -17., 0])
np.linalg.solve(M1, v1)

array([1., 2., 3.])

Видим, что корни найдены правильно

    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
 
Запишем уравнение в матричном виде и воспользуемся функцией.

In [6]:
A = np.array([[2., -4., 6., 1.], [1, -2, 3, -2], [3, -6, 9, 5]])
A

array([[ 2., -4.,  6.,  1.],
       [ 1., -2.,  3., -2.],
       [ 3., -6.,  9.,  5.]])

In [7]:
solv_equations(A)

Диагональная матрица:
[[ 2.  -4.   6.   1. ]
 [ 0.   0.   0.  -2.5]
 [ nan  nan  nan  nan]]
Диагональная матрица:
[[ 2.  -4.   6.   1. ]
 [ 0.   0.   0.  -2.5]
 [ nan  nan  nan  nan]]
Данная СЛАУ является несовместной и решений не имеет


In [8]:
M1 = np.array([[2., -4., 6.], [1, -2, 3], [3, -6, 9]])
v1 = np.array([1., -2., 5])
np.linalg.solve(M1, v1)

LinAlgError: Singular matrix

Видим, что данное СЛАУ действительно не имеет решний

в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

Запишем уравнение в матричном виде и воспользуемся функцией.

In [9]:
A = np.array([[1., 2., 5., 4.], [3, 1, -8, -2]])
A

array([[ 1.,  2.,  5.,  4.],
       [ 3.,  1., -8., -2.]])

In [10]:
solv_equations(A)

Диагональная матрица:
[[  1.   2.   5.   4.]
 [  0.  -5. -23. -14.]]
Диагональная матрица:
[[  1.   2.   5.   4.]
 [  0.  -5. -23. -14.]]
Данная СЛАУ является совместной и имеет бесконечное множество решений


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Запишем уравнение в матричном виде и воспользуемся функцией.

In [11]:
A = np.array([[1., 3., -2., 4., 3.], [0., 5., 0., 1., 2.], [0., 0., 3., 0., 4.], [0., 0., 0., 2., 1.]])
A

array([[ 1.,  3., -2.,  4.,  3.],
       [ 0.,  5.,  0.,  1.,  2.],
       [ 0.,  0.,  3.,  0.,  4.],
       [ 0.,  0.,  0.,  2.,  1.]])

In [12]:
solv_equations(A)

Диагональная матрица:
[[ 1.  3. -2.  4.  3.]
 [ 0.  5.  0.  1.  2.]
 [ 0.  0.  3.  0.  4.]
 [ 0.  0.  0.  2.  1.]]
Данная СЛАУ является совместной со следующими корнями:  [2.7666666666666666, 0.3, 1.3333333333333333, 0.5]


Проверим

In [13]:
M1 = np.array([[1., 3., -2., 4.], [0., 5., 0., 1.], [0., 0., 3., 0.], [0., 0., 0., 2.]])
v1 = np.array([ 3., 2., 4., 1.])
np.linalg.solve(M1, v1)

array([2.77, 0.3 , 1.33, 0.5 ])

Видим, что корни найдены правильно

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

После преобразования расширенной матрицы данной системы линейных уравнений путем элементарных преобразований получаем следующую диагональную матрицу:  

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
-4a + b\\
a - 2b + с
\end{matrix}
\end{pmatrix}.$$

Из данной диагональной матрицы мы видим, что система будет несовместной при условии, что $a - 2b + с \neq 0$. Если $a - 2b + с = 0$, то сисема будет иметь бесконечное множество решений.