## Практическое задание 3

In [1]:
import sympy as sym
import numpy as np
np.set_printoptions(precision=2, suppress=True)

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)-2\cdot(-6)=0,$$  
Решим данное уравнение

In [2]:
x = sym.Symbol('x')
sym.solveset((-1-x)*(6-x)-2*(-6))

{2, 3}

##### Видим, что собственные значения равны 2 и 3

##### Найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$ для собственного значения 2, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
2
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим

$$\begin{cases}
-x_{1}-6x_{2}= 2x_{1}, \\
2\cdot x_{1}+6x_{2}= 2x_{2}.
\end{cases}$$

$$\begin{cases}
-3x_{1}-6x_{2}= 0, \\
2x_{1}+4x_{2}= 0.
\end{cases}$$

$$x_{1} = -2x_{2}$$
 Из этого уравнения следует, что вектор вида $x=\begin{pmatrix}
2\\ 
-1
\end{pmatrix}$ удовлетворяет каждому уравнению системы.  
Таким образом, существует множество коллинеарных друг другу собственных векторов, представителем которых является $x=(2, -1)$ (с точностью до умножения на число), которые это линейное преобразование переводит в коллинеарные исходным.

Найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$ для собственного значения 3, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
3
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим

$$\begin{cases}
-x_{1}-6x_{2}= 2x_{1}, \\
2\cdot x_{1}+6x_{2}= 2x_{2}.
\end{cases}$$

$$\begin{cases}
-3x_{1}-6x_{2}= 0, \\
2x_{1}+4x_{2}= 0.
\end{cases}$$

$$x_{1} = -2x_{2}$$
 Из этого уравнения следует, что вектор вида $x=\begin{pmatrix}
2\\ 
-1
\end{pmatrix}$ удовлетворяет каждому уравнению системы.  
Таким образом, существует множество коллинеарных друг другу собственных векторов, представителем которых является $x=(2, -1)$ (с точностью до умножения на число), которые это линейное преобразование переводит в коллинеарные исходным.

##### Найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$ для собственного значения 3, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
3
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим

$$\begin{cases}
-x_{1}-6x_{2}= 3x_{1}, \\
2\cdot x_{1}+6x_{2}= 3x_{2}.
\end{cases}$$

$$\begin{cases}
-4x_{1}-6x_{2}= 0, \\
2x_{1}+3x_{2}= 0.
\end{cases}$$

$$x_{1} = -1,5x_{2}$$
 Из этого уравнения следует, что вектор вида $x=\begin{pmatrix}
3\\ 
-2
\end{pmatrix}$ удовлетворяет каждому уравнению системы.  
Таким образом, существует множество коллинеарных друг другу собственных векторов, представителем которых является $x=(3, -2)$ (с точностью до умножения на число), которые это линейное преобразование переводит в коллинеарные исходным. Проверим

In [3]:
A = np.array([[-1, -6], [2, 6]])
x_1 = np.array([2, -1])
x_2 = np.array([3, -2])
w, v = np.linalg.eig(A)
 
print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


Проверим через выражение $\textbf{A}x=\lambda x$

In [4]:
A @ x_1 == 2 * x_1

array([ True,  True])

In [5]:
A @ x_2 == 3 * x_2

array([ True,  True])

Видим, что собственные вектора и собственные значения были посчитаны верно.

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(-1-\lambda)=0,$$  
Решим данное уравнение

In [6]:
x = sym.Symbol('x')
sym.solveset((-1-x)*(-1-x))

{-1}

##### Найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$ для собственного значения -1, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
-
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим

$$\begin{cases}
-x_{1}= -x_{1}, \\
-x_{2}= -x_{2}.
\end{cases}$$
Видим, что данная система имеет решение при любых $x_{1}$ и $x_{2}$, следовательно __любой__ вектор является собственным для оператора $$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Проверим

In [7]:
A = np.array([[-1, 0], [0, -1]])
x_1 = np.random.rand(2,2)

w, v = np.linalg.eig(A)
 
print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


In [8]:
A @ x_1 == -x_1

array([[ True,  True],
       [ True,  True]])

Действительно видим, что любой случайный вектор является собственным для рассматриваемого оператора

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

Для ответа на этот вопрос воспользуемся выражением $\textbf{A}x=\lambda x$.  
Составим и попробуем решить уравнение  
$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

Получим

$$\begin{cases}
2 = \lambda, \\
2 = \lambda.
\end{cases}$$  
Таким образом, видим, что при собственом значении 2 вектор $x=(1,1)$ является собственным для матрицы $$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$ 

In [9]:
A = np.array([[1, 1], [-1, 3]])
x_1 = np.array([1, 1])

w, v = np.linalg.eig(A)
 
print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


In [10]:
A @ x_1 == 2 * x_1

array([ True,  True])

Проверка подтвердила, что при собственом значении 2 вектор $x=(1,1)$ является собственным для матрицы $$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$ 

**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

Для ответа на этот вопрос воспользуемся выражением $\textbf{A}x=\lambda x$.  
Составим и попробуем решить уравнение  
$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

Получим

$$\Rightarrow
\begin{cases}
-9 = \lambda 3\\ 
-9 = \lambda 3\\
-12 = -\lambda 4
\end{cases}$$

Такая система не имеет смысла, следовательно, вектор $x=(3,-3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$. Проверим 

In [11]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
x_1 = np.array([3, -3, -4])

w, v = np.linalg.eig(A)
 
print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]


In [12]:
A @ x_1 == 3 * x_1

array([False, False,  True])

In [13]:
A @ x_1 == -3 * x_1

array([ True,  True, False])

Проверка подтвердила, что при собственых значениях 3 и -3 вектор $x=(3, -3, -4)$ не является собственным для матрицы $$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}$$ 